// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-DIoTCzVEu63yZE_FBUGfjYlY8vSJoA',
    appId: '1:295452671260:web:4ed506eb519dbc244e4ed9',
    messagingSenderId: '295452671260',
    projectId: 'my-lab2-mis',
    authDomain: 'my-lab2-mis.firebaseapp.com',
    storageBucket: 'my-lab2-mis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAajau96pDtGT8To_V3TWGbOX7HqB_cxMY',
    appId: '1:295452671260:android:182e51c4b75a7aae4e4ed9',
    messagingSenderId: '295452671260',
    projectId: 'my-lab2-mis',
    storageBucket: 'my-lab2-mis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosQ5Aamvgnru7gNggTICtWre3xzqcwWc',
    appId: '1:295452671260:ios:7df01bdfcdc39afd4e4ed9',
    messagingSenderId: '295452671260',
    projectId: 'my-lab2-mis',
    storageBucket: 'my-lab2-mis.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDosQ5Aamvgnru7gNggTICtWre3xzqcwWc',
    appId: '1:295452671260:ios:7df01bdfcdc39afd4e4ed9',
    messagingSenderId: '295452671260',
    projectId: 'my-lab2-mis',
    storageBucket: 'my-lab2-mis.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj-DIoTCzVEu63yZE_FBUGfjYlY8vSJoA',
    appId: '1:295452671260:web:c15b27609d81315c4e4ed9',
    messagingSenderId: '295452671260',
    projectId: 'my-lab2-mis',
    authDomain: 'my-lab2-mis.firebaseapp.com',
    storageBucket: 'my-lab2-mis.firebasestorage.app',
  );

}